import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";

// Ładowanie lokalnych czcionek do projektu
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Meta dane dla strony
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Główna struktura layoutu aplikacji
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Nawigacja na każdej stronie */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
