"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// Meta dane dla strony
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Główna struktura layoutu aplikacji
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        {/* Nawigacja na każdej stronie */}
        <NavBar />

        {children}
      </body>
    </html>
  );
}
